Feature/update personal information
rent-space/rent-space-backend pull request #28
Opened 2024-04-14 02:43 UTC by soaresmaric

Fale mal, vá, seu marombeiro maconheiro...........

2024-04-14 13:06 UTC, viniciussousaazevedo requested changes

2024-04-14 13:06 UTC, viniciussousaazevedo commented on src/main/java/com/rentspace/service/PlaceService.java
> +                .orElseThrow(() -> new ApiRequestException(INVALID_PLACE_ID + placeId));
altera a mensagem que retorna pra que sirva tanto pra produto quanto serviço, a nível de produto, daí podemos reutilizar mais

2024-04-14 13:06 UTC, viniciussousaazevedo commented on src/main/java/com/rentspace/service/ServiceService.java
> +                .orElseThrow(() -> new ApiRequestException(INVALID_SERVICE_ID + id));
altera a mensagem que retorna pra que sirva tanto pra produto quanto serviço, a nível de produto, daí podemos reutilizar mais

2024-04-14 13:06 UTC, viniciussousaazevedo commented on src/main/java/com/rentspace/service/UserService.java
> +                .orElseThrow(() -> new ApiRequestException(USER_EMAIL_NOT_FOUND + id));
mensagem de erro sobre email, mas o erro é com base na busca por id

2024-04-14 13:06 UTC, viniciussousaazevedo commented on src/main/java/com/rentspace/service/UserService.java
> +        AppUser user = userRepository.findById(id)
aqui pode usar o método get(id)

2024-04-14 13:06 UTC, viniciussousaazevedo commented on src/main/java/com/rentspace/service/UserService.java
> +        user = buildUser(user, persistUserDTO);
alterar assinatura do método buildUser() para se encaixar no padrão já existente

2024-04-14 13:06 UTC, viniciussousaazevedo commented on src/main/java/com/rentspace/util/ModelMapperFuncs.java
> +        appUser.setEmail(dto.getTelephone());
setando telefone para o campo email

2024-04-14 13:06 UTC, viniciussousaazevedo commented on src/main/java/com/rentspace/util/ModelMapperFuncs.java
> +    public AppUser buildUser(AppUser appUser, PersistUserDTO dto) {
aqui não bastaria fazer um map do modelMapper?

2024-04-14 13:19 UTC, soaresmaric commented on src/main/java/com/rentspace/service/UserService.java
> +                .orElseThrow(() -> new ApiRequestException(USER_EMAIL_NOT_FOUND + id));
errei fui mlk

2024-04-14 13:19 UTC, soaresmaric commented on src/main/java/com/rentspace/util/ModelMapperFuncs.java
> +        appUser.setEmail(dto.getTelephone());
foi o sono

2024-04-14 13:20 UTC, soaresmaric commented on src/main/java/com/rentspace/util/ModelMapperFuncs.java
> +    public AppUser buildUser(AppUser appUser, PersistUserDTO dto) {
não funciona, ele não associa as mudanças ao usuário que já existe no banco e cria um novo

2024-04-15 14:13 UTC, viniciussousaazevedo requested changes

2024-04-15 14:13 UTC, viniciussousaazevedo commented on src/main/java/com/rentspace/controller/PlaceReservationController.java
> +        return new ResponseEntity<>("Reserva de espaço removida com sucesso", HttpStatus.OK);
retorna o objeto deletado nos endpoints

2024-04-15 14:13 UTC, viniciussousaazevedo commented on src/main/java/com/rentspace/util/ModelMapperFuncs.java
> +        appUser.setEmail(dto.getTelephone());
```suggestion
        appUser.setTelephone(dto.getTelephone());
```

2024-04-15 14:15 UTC, viniciussousaazevedo commented on src/main/java/com/rentspace/util/ModelMapperFuncs.java
> +        appUser.setEmail(dto.getTelephone());
Não tem como usar o modelmapper nisso?

2024-04-16 00:48 UTC, soaresmaric commented on src/main/java/com/rentspace/util/ModelMapperFuncs.java
> +        appUser.setEmail(dto.getTelephone());
Não, usando modelMapper ele fica criando novos usuários a cada update. Setando dessa forma, ele associa ao usuario que a gente passou a url no id

2024-04-16 00:50 UTC, soaresmaric commented on src/main/java/com/rentspace/util/ModelMapperFuncs.java
> +        appUser.setEmail(dto.getTelephone());
resolvi o set errado.

2024-04-16 00:56 UTC, soaresmaric commented on src/main/java/com/rentspace/service/ServiceService.java
> +                .orElseThrow(() -> new ApiRequestException(INVALID_SERVICE_ID + id));
não saquei

2024-04-16 12:18 UTC, viniciussousaazevedo commented on src/main/java/com/rentspace/util/ModelMapperFuncs.java
> +        appUser.setEmail(dto.getEmail());
```suggestion
        appUser.setEmail(dto.getEmail());
        appUser.setTelephone(dto.getTelephone());
```

2024-04-16 12:18 UTC, viniciussousaazevedo approved these changes

2024-04-16 13:18 UTC, merged